### ISSUE TITLE
[Tracking User Data] Picture/Images

### ISSUE THREAD

**Issue by Daljin** [acm-projects/closet-hangr#21]
- [x] Ask for a solid background (Front end)
- [x] Cut out background and leave the clothes.
    ~~*Use [starflut](https://pub.dev/packages/starflut#-readme-tab-) to use the [removebg api](https://www.remove.bg/api)~~
   ~~*Use [tflite plugin](https://pub.dev/packages/tflite#-readme-tab-) to access [Tensorflow's image segmentation model](https://www.tensorflow.org/lite/models/segmentation/overview).~~
- [x] Pick clothes from the internet to test.
- [x] Implement Camera feature in app (front end)
- [x] Connect camera and background removal
