### ISSUE TITLE
[Tracking User Data] Create a database

### ISSUE THREAD

**Issue by NoahAGonzales** [acm-projects/closet-hangr#25]
- [x] Use Appsync to host database
- [x] Learn graphql
        - [ ] [Schema](https://docs.aws.amazon.com/appsync/latest/devguide/designing-your-schema.html)
- [x] Structure Database
- [x] Allow images in the database
    - [x] [ Permissions Allowing](https://docs.expo.io/versions/latest/sdk/permissions/#permissionsuser_facing_notifications)
    - [x] [Camera roll/Camera Access](https://docs.expo.io/versions/latest/sdk/imagepicker/)
    - [x] Image Wrapper ([blob](https://github.com/joltup/rn-fetch-blob))
    - [x] S3 Integration - 
        - Tutorials: [1](https://read.acloud.guru/build-your-own-multi-user-photo-album-app-with-react-graphql-and-aws-amplify-18d9cfe27f60) [2](https://www.youtube.com/watch?v=FXG3AJ6OJCk) [3](https://www.youtube.com/watch?v=5YkGYB0qdzc&list=WL&index=11&t=0s) [w/blob](https://medium.com/@ballenwillis/react-native-write-files-to-s3-with-aws-amplify-f4b32f96d22e)
        - [S3 API Documentation](https://aws-amplify.github.io/docs/js/storage) and [Details](https://aws-amplify.github.io/amplify-js/api/classes/storageclass.html#put)
